import type { Ticket } from "../types/tickets.types";

export const MOCK_TICKETS: Ticket[] = [
  {
    id: "CAT-10245",
    helixId: "INC0012458",
    site: "Zapopan Centro",
    category: "Conectividad",
    attendedBy: "Carlos M.",
    status: "created",
    slaResponse: "ok",
    slaResolution: "warning",
  },
  {
    id: "CAT-10244",
    helixId: "INC0012457",
    site: "Planta Norte",
    category: "WiFi",
    attendedBy: "Ana R.",
    status: "assigned",
    slaResponse: "ok",
    slaResolution: "ok",
  },
  {
    id: "CAT-10243",
    helixId: "INC0012456",
    site: "Campus 3K",
    category: "Red LAN",
    attendedBy: "Luis G.",
    status: "in-progress",
    slaResponse: "warning",
    slaResolution: "warning",
  },
  {
    id: "CAT-10242",
    helixId: "INC0012455",
    site: "Oficinas Centrales",
    category: "Hardware",
    attendedBy: "María T.",
    status: "paused",
    slaResponse: "ok",
    slaResolution: "danger",
  },
  {
    id: "CAT-10241",
    helixId: "INC0012454",
    site: "Sucursal Sur",
    category: "Telefonía",
    attendedBy: "Jorge P.",
    status: "resolved",
    slaResponse: "ok",
    slaResolution: "ok",
  },
  {
    id: "CAT-10240",
    helixId: "INC0012453",
    site: "Planta Oriente",
    category: "Proveedor",
    attendedBy: "Sin asignar",
    status: "quotation",
    slaResponse: "warning",
    slaResolution: "danger",
  },
];