import { PERMISSIONS, type Permission } from "./permissions";

import { ROLES, type Role } from "./roles";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.NOC_SUPERVISOR]: [
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_DASHBOARD_VIEW,
    PERMISSIONS.TICKET_VIEW_ALL,
    PERMISSIONS.TICKET_TABLE_VIEW,

    PERMISSIONS.TICKET_EDIT,
    PERMISSIONS.TICKET_MANAGE,
    PERMISSIONS.TICKET_DELETE,

    // Estado
    PERMISSIONS.TICKET_START,
    PERMISSIONS.TICKET_STATUS_CHANGE,
    PERMISSIONS.TICKET_PAUSE,

    // Gestión relacionada
    PERMISSIONS.TICKET_DEPENDENCIES_MANAGE,
    PERMISSIONS.TICKET_RELATED_MANAGE,

    PERMISSIONS.TICKET_NOTES_MANAGE,
    PERMISSIONS.TICKET_OBJECTS_DELETE,
    PERMISSIONS.TICKET_DOCUMENTS_DOWNLOAD,
    PERMISSIONS.TICKET_REPORT_DOWNLOAD,

    PERMISSIONS.TICKET_SITE_EDIT,
    PERMISSIONS.TICKET_SITE_ADDRESS_CHANGE,

    PERMISSIONS.TICKET_IMAGES_VIEW,
    PERMISSIONS.TICKET_IMAGES_UPLOAD,

    PERMISSIONS.TICKET_ACTIVITIES_REPORT,

    PERMISSIONS.TICKET_REPLACEMENTS_REPORT,
    PERMISSIONS.TICKET_INTERVENTIONS_REPORT,

    PERMISSIONS.TICKET_PROVIDER_ASSIGN,

    PERMISSIONS.SITES_VIEW,
    PERMISSIONS.SITES_CREATE,
    PERMISSIONS.SITES_EDIT,
    PERMISSIONS.SITES_DELETE,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.IMPLEMENTATIONS_CREATE,

    PERMISSIONS.USERS_DEACTIVATE,
    PERMISSIONS.NOC_USERS_VIEW,

    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.DASHBOARD_GRAPH_VIEW,
  ],

  [ROLES.AGENTE_RJ]: [
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_DASHBOARD_VIEW,
    PERMISSIONS.TICKET_VIEW_ALL,
    PERMISSIONS.TICKET_TABLE_VIEW,

    PERMISSIONS.TICKET_EDIT,
    PERMISSIONS.TICKET_MANAGE,

    // Estado
    PERMISSIONS.TICKET_START,
    PERMISSIONS.TICKET_STATUS_CHANGE,
    PERMISSIONS.TICKET_PAUSE,

    // Gestión relacionada
    PERMISSIONS.TICKET_DEPENDENCIES_MANAGE,
    PERMISSIONS.TICKET_RELATED_MANAGE,

    PERMISSIONS.TICKET_NOTES_MANAGE,
    PERMISSIONS.TICKET_DOCUMENTS_DOWNLOAD,
    PERMISSIONS.TICKET_REPORT_DOWNLOAD,

    PERMISSIONS.TICKET_SITE_EDIT,
    PERMISSIONS.TICKET_SITE_ADDRESS_CHANGE,

    PERMISSIONS.TICKET_IMAGES_VIEW,
    PERMISSIONS.TICKET_IMAGES_UPLOAD,

    PERMISSIONS.TICKET_ACTIVITIES_REPORT,

    PERMISSIONS.TICKET_REPLACEMENTS_REPORT,
    PERMISSIONS.TICKET_INTERVENTIONS_REPORT,

    PERMISSIONS.SITES_VIEW,
    PERMISSIONS.SITES_CREATE,
    PERMISSIONS.SITES_EDIT,

    PERMISSIONS.PROJECTS_VIEW,

    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.DASHBOARD_GRAPH_VIEW,
  ],

  [ROLES.AGENTE_PGH]: [
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_DASHBOARD_VIEW,
    PERMISSIONS.TICKET_VIEW_ALL,
    PERMISSIONS.TICKET_TABLE_VIEW,

    PERMISSIONS.TICKET_EDIT,
    PERMISSIONS.TICKET_MANAGE,

    // Estado
    PERMISSIONS.TICKET_START,
    PERMISSIONS.TICKET_STATUS_CHANGE,
    PERMISSIONS.TICKET_PAUSE,

    // Gestión relacionada
    PERMISSIONS.TICKET_DEPENDENCIES_MANAGE,
    PERMISSIONS.TICKET_RELATED_MANAGE,

    PERMISSIONS.TICKET_NOTES_MANAGE,
    PERMISSIONS.TICKET_DOCUMENTS_DOWNLOAD,
    PERMISSIONS.TICKET_REPORT_DOWNLOAD,

    PERMISSIONS.TICKET_SITE_EDIT,
    PERMISSIONS.TICKET_SITE_ADDRESS_CHANGE,

    PERMISSIONS.TICKET_IMAGES_VIEW,
    PERMISSIONS.TICKET_IMAGES_UPLOAD,

    PERMISSIONS.TICKET_ACTIVITIES_REPORT,

    PERMISSIONS.TICKET_REPLACEMENTS_REPORT,
    PERMISSIONS.TICKET_INTERVENTIONS_REPORT,

    PERMISSIONS.TICKET_PROVIDER_ASSIGN,

    PERMISSIONS.SITES_VIEW,
    PERMISSIONS.SITES_CREATE,
    PERMISSIONS.SITES_EDIT,

    PERMISSIONS.PROJECTS_VIEW,

    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.DASHBOARD_GRAPH_VIEW,
  ],

  [ROLES.COORDINADOR_OPERATIVO]: [
    PERMISSIONS.TICKET_DASHBOARD_VIEW,
    PERMISSIONS.TICKET_VIEW_ALL,
    PERMISSIONS.TICKET_TABLE_VIEW,

    PERMISSIONS.TICKET_SITE_EDIT,
    PERMISSIONS.TICKET_IMAGES_VIEW,
    PERMISSIONS.TICKET_MATERIALS_VIEW,
    PERMISSIONS.TICKET_NOTES_MANAGE,

    PERMISSIONS.TICKET_SUPERVISOR_ASSIGN,
    PERMISSIONS.TICKET_LEADER_CHANGE,

    PERMISSIONS.SITES_VIEW,
    PERMISSIONS.SITES_EDIT,

    PERMISSIONS.PROFILE_VIEW,
  ],

  [ROLES.LIDER_OPERATIVO]: [
    PERMISSIONS.TICKET_DASHBOARD_VIEW,
    PERMISSIONS.TICKET_VIEW_ALL,
    PERMISSIONS.TICKET_TABLE_VIEW,

    PERMISSIONS.TICKET_SITE_EDIT,
    PERMISSIONS.TICKET_IMAGES_VIEW,
    PERMISSIONS.TICKET_MATERIALS_VIEW,
    PERMISSIONS.TICKET_NOTES_MANAGE,

    PERMISSIONS.SITES_VIEW,
    PERMISSIONS.SITES_EDIT,

    PERMISSIONS.PROFILE_VIEW,
  ],

  [ROLES.SUPERVISOR]: [
    PERMISSIONS.TICKET_DASHBOARD_VIEW,
    PERMISSIONS.TICKET_VIEW_ALL,

    PERMISSIONS.TICKET_SITE_EDIT,
    PERMISSIONS.TICKET_IMAGES_VIEW,
    PERMISSIONS.TICKET_MATERIALS_VIEW,
    PERMISSIONS.TICKET_MATERIALS_VALIDATE,
    PERMISSIONS.TICKET_NOTES_MANAGE,

    PERMISSIONS.TICKET_PROVIDER_ASSIGN,

    PERMISSIONS.SITES_VIEW,
    PERMISSIONS.SITES_EDIT,

    PERMISSIONS.PROFILE_VIEW,
  ],

  [ROLES.ANALISTA]: [
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_DASHBOARD_VIEW,
    PERMISSIONS.TICKET_VIEW_ALL,
    PERMISSIONS.TICKET_TABLE_VIEW,
    PERMISSIONS.TICKET_NOTES_MANAGE,
    PERMISSIONS.TICKET_DOCUMENTS_DOWNLOAD,
    PERMISSIONS.TICKET_REPORT_DOWNLOAD,

    PERMISSIONS.TICKET_SITE_EDIT,

    PERMISSIONS.TICKET_IMAGES_VIEW,
    PERMISSIONS.TICKET_IMAGES_UPLOAD,

    PERMISSIONS.TICKET_ACTIVITIES_REPORT,

    PERMISSIONS.SITES_VIEW,
    PERMISSIONS.SITES_CREATE,
    PERMISSIONS.SITES_EDIT,

    PERMISSIONS.TAGGING_VIEW,
    PERMISSIONS.TAGGING_EDIT,
    PERMISSIONS.TAGGING_VALIDATE,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.IMPLEMENTATIONS_CREATE,

    PERMISSIONS.PROFILE_VIEW,
  ],

  [ROLES.AGENTE_SERVICIOS]: [
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_DASHBOARD_VIEW,
    PERMISSIONS.TICKET_VIEW_ALL,
    PERMISSIONS.TICKET_TABLE_VIEW,
    PERMISSIONS.TICKET_NOTES_MANAGE,
    PERMISSIONS.TICKET_DOCUMENTS_DOWNLOAD,
    PERMISSIONS.TICKET_REPORT_DOWNLOAD,

    PERMISSIONS.TICKET_IMAGES_VIEW,
    PERMISSIONS.TICKET_IMAGES_UPLOAD,

    PERMISSIONS.TICKET_ACTIVITIES_REPORT,
    PERMISSIONS.TICKET_REPLACEMENTS_REPORT,
    PERMISSIONS.TICKET_PROVIDER_ASSIGN,

    PERMISSIONS.SITES_VIEW,
    PERMISSIONS.SITES_CREATE,
    PERMISSIONS.SITES_EDIT,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_DELETE,
    PERMISSIONS.PROJECTS_MANAGE,
    PERMISSIONS.IMPLEMENTATIONS_CREATE,

    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.DASHBOARD_GRAPH_VIEW,
  ],

  [ROLES.VISOR]: [
    PERMISSIONS.TICKET_DASHBOARD_VIEW,
    PERMISSIONS.TICKET_VIEW_ALL,
    PERMISSIONS.TICKET_TABLE_VIEW,
    PERMISSIONS.TICKET_DOCUMENTS_DOWNLOAD,
    PERMISSIONS.TICKET_REPORT_DOWNLOAD,
    PERMISSIONS.TICKET_IMAGES_VIEW,

    PERMISSIONS.SITES_VIEW,
    PERMISSIONS.PROJECTS_VIEW,

    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.DASHBOARD_GRAPH_VIEW,
  ],

  [ROLES.SOPORTE]: [
    PERMISSIONS.TICKET_DASHBOARD_VIEW,
    PERMISSIONS.TICKET_SUPPORT_VIEW,
    PERMISSIONS.TICKET_MANAGE,

    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.SUPPORT_METRICS_VIEW,
  ],

  [ROLES.CLIENTE]: [
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_VIEW_INFO,
    PERMISSIONS.TICKET_TABLE_VIEW,

    PERMISSIONS.TICKET_IMAGES_VIEW,
    PERMISSIONS.TICKET_IMAGES_UPLOAD,

    PERMISSIONS.TICKET_ACTIVITIES_REPORT,

    PERMISSIONS.SITES_VIEW,

    PERMISSIONS.PROFILE_VIEW,
  ],

  [ROLES.LIDER_CUADRILLA]: [PERMISSIONS.TICKET_CREW_ASSIGN],

  [ROLES.USUARIO_CUADRILLA]: [
    PERMISSIONS.TICKET_ACTIVITIES_REPORT_APP,
    PERMISSIONS.TICKET_IMAGES_UPLOAD,
    PERMISSIONS.TICKET_MATERIALS_REPORT,
    PERMISSIONS.TICKET_REPLACEMENTS_REPORT,
    PERMISSIONS.SITES_TAG,
  ],
};
