export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  NOC_SUPERVISOR: "NOC_SUPERVISOR",
  AGENTE_RJ: "AGENTE_RJ",
  AGENTE_PGH: "AGENTE_PGH",
  COORDINADOR_OPERATIVO: "COORDINADOR_OPERATIVO",
  LIDER_OPERATIVO: "LIDER_OPERATIVO",
  SUPERVISOR: "SUPERVISOR",
  ANALISTA: "ANALISTA",
  AGENTE_SERVICIOS: "AGENTE_SERVICIOS",
  VISOR: "VISOR",
  SOPORTE: "SOPORTE",
  CLIENTE: "CLIENTE",
  LIDER_CUADRILLA: "LIDER_CUADRILLA",
  USUARIO_CUADRILLA: "USUARIO_CUADRILLA",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const NOC_ROLES: Role[] = [
  ROLES.NOC_SUPERVISOR,
  ROLES.AGENTE_RJ,
  ROLES.AGENTE_PGH,
];
